font_family InconsolataLGCNerdFont
bold_font InconsolataLGCNerdFont
italic_font InconsolataLGCNerdFont
bold_italic_font InconsolataLGCNerdFont
font_size 14.0

remember_window_size no
initial_window_width 100
initial_window_height 30
window_padding_width 10
hide_window_decorations yes

cursor_shape block
cursor_blink_interval 0

scrollback_lines 10000

detect_urls yes
enable_audio_bell no

background #242933
foreground #BBBDAF

color0 #191C1D
color1 #BD6062
color2 #A3D6A9
color3 #F0DFAF
color4 #8FB4D8
color5 #C7A9D9
color6 #B6D7A8
color7 #BDC5BD

color8 #727C7C
color9 #D18FAF
color10 #B7CEB0
color11 #BCBCBC
color12 #E0CF9F
color13 #C7A9D9
color14 #BBDA97
color15 #BDC5BD

selection_foreground #000000
selection_background #F0DFAF
