Vertical Candidate List=False
WheelForPaging=True
Font="Noto Sans CJK SC 10"
MenuFont="Noto Sans CJK SC 10"
TrayFont="JetBrains Mono Bold 10"
TrayOutlineColor=#000000
TrayTextColor=#ffffff
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True
Theme=FluentLight-solid
DarkTheme=FluentLight-solid
UseDarkTheme=False
UseAccentColor=True
PerScreenDPI=False
ForceWaylandDPI=0
EnableFractionalScale=True

