[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
linemode = "mtime"
show_hidden = true

[preview]
wrap = "yes"

[opener]
imv = [
    { run = 'imv "$@"', block = true, desc = "Image Viewer" },
]
zathura = [
    { run = 'zathura "$@"', block = true, desc = "PDF Reader" },
]
epr = [
    { run = 'epr "$@"', block = true, desc = "EPUB Reader" },
]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix", desc = "Media Player" },
]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix", desc = "Text Editor" },
]
open = [
    { run = 'xdg-open "$@"', desc = "System Default" },
]

[open]
prepend_rules = [
    { url = "*.{json,sh,toml,yml,yaml,cfg,ini,lua,xml}", use = "edit" },
    { url = "*.{md,txt,log}", use = "edit" },
    { url = ".*{zsh*,env,config}", use = "edit" },
    { url = "*.{jpg,png,jpeg,gif,svg,bmp}", use = "imv" },
    { url = "*.{mp3,mp4,flac,mkv,avi,wav}", use = "play" },
    { url = "*.{pdf}", use = "zathura" },
    { url = "*.{epub}", use = "epr" },
    { url = "*.{ods,xlsx,csv,docx}", use = "open" },
]
append_rules = [
    { url = "*", use = "edit" },
]
