[mgr]
ratio = [1, 3, 4]
sort_by = "mtime"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
linemode = "none"
show_hidden = true

[preview]
wrap = "yes"
ueberzug_scale = 0.1


[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '"$EDITOR" "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
	{ run = 'epr "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },
	{ name = "*.sh", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.y*ml", use = "edit" },
	{ name = "*config", use = "edit" },
	{ name = "*.cfg", use = "edit" },
	{ name = "*env", use = "edit" },
	{ name = "*.d", use = "edit" },
	{ name = "*.md", use = "edit" },
	{ name = "*.txt", use = "edit" },
	{ name = ".zsh*", use = "edit" },
	{ name = "*.ini", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.xml", use = "edit" },
	{ name = "*.log", use = "edit" },
	{ name = "*.ods", use = "open" },
	{ name = "*.pdf", use = "open" },
	{ name = "*.epub", use = "open" },
	{ name = "*.mp3", use = "play" },

]
append_rules = [
	{ name = "*", use = "edit" },
]

